# Generated by Django 4.0.4 on 2022-05-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem_alter_servico_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('recurso', models.CharField(max_length=100, verbose_name='Recurso:')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'CamadaFolhas'), ('lni-laptop-phone', 'LaptopMobile'), ('lni-rocket', 'Foguete')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
